/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import type { ConfigurationBuilderState, ConfigValues } from "@/types/configuration-builder";
import { isPlainObject } from "./value-guards";
import { getByPath } from "./config-path";

const INSTRUMENTATION_PATH = ["distribution", "javaagent", "instrumentation"];

function readInstrumentationLists(values: ConfigValues): {
  enabled: string[];
  disabled: string[];
} {
  const current = getByPath(values, INSTRUMENTATION_PATH);
  const inst = isPlainObject(current) ? current : {};
  return {
    enabled: Array.isArray(inst.enabled) ? (inst.enabled as string[]) : [],
    disabled: Array.isArray(inst.disabled) ? (inst.disabled as string[]) : [],
  };
}

// Converts a module name like "http-url-connection" to "HTTP_URL_CONNECTION"
function moduleNameToEnvFragment(name: string): string {
  return name.toUpperCase().replace(/-/g, "_");
}

export interface OutputFormatOptions {
  javaAgentVersion?: string;
}

function buildEnvVarHeader(date: string, javaAgentVersion?: string): string[] {
  const lines = [
    "# OpenTelemetry Java Agent - Instrumentation Settings",
    "# Generated by Ecosystem Explorer",
    `# Generated on ${date}`,
  ];
  if (javaAgentVersion) {
    lines.push(`# Java agent: ${javaAgentVersion}`);
  }
  lines.push(
    "#",
    "# Set these as environment variables before starting your application:",
    "#   export OTEL_INSTRUMENTATION_JDBC_ENABLED=false",
    "#",
    "# SDK-level settings (exporters, samplers, resource) are configured via",
    "# the declarative YAML file. Switch to the YAML format to get that output.",
    "#"
  );
  return lines;
}

function buildSysPropHeader(date: string, javaAgentVersion?: string): string[] {
  const lines = [
    "# OpenTelemetry Java Agent - JVM System Properties",
    "# Generated by Ecosystem Explorer",
    `# Generated on ${date}`,
  ];
  if (javaAgentVersion) {
    lines.push(`# Java agent: ${javaAgentVersion}`);
  }
  lines.push(
    "#",
    "# Pass these as JVM arguments when launching your application:",
    "#   java -Dotel.instrumentation.jdbc.enabled=false -jar app.jar",
    "#",
    "# SDK-level settings (exporters, samplers, resource) are configured via",
    "# the declarative YAML file. Switch to the YAML format to get that output.",
    "#"
  );
  return lines;
}

const NO_CUSTOMIZATIONS_LINES = [
  "# No instrumentation customizations configured.",
  "# All instrumentations are using their default enabled state.",
];

/**
 * Generates environment variable output for the instrumentation settings
 * currently assembled in the configuration builder.
 *
 * Each explicitly enabled or disabled instrumentation is rendered as an
 * OTEL_INSTRUMENTATION_<NAME>_ENABLED=true/false line. SDK-level settings
 * (exporters, samplers, resource) live in the declarative YAML and do not
 * have a direct env var equivalent that can be auto-derived from the YAML
 * structure, so they are not included here.
 */
export function generateEnvVars(
  state: ConfigurationBuilderState,
  options?: OutputFormatOptions
): string {
  const date = new Date().toISOString().slice(0, 10);
  const { enabled, disabled } = readInstrumentationLists(state.values);
  const lines = buildEnvVarHeader(date, options?.javaAgentVersion);
  lines.push("");

  if (enabled.length === 0 && disabled.length === 0) {
    lines.push(...NO_CUSTOMIZATIONS_LINES);
    return lines.join("\n") + "\n";
  }

  if (enabled.length > 0) {
    lines.push("# Explicitly enabled instrumentations");
    for (const name of [...enabled].sort()) {
      lines.push(`OTEL_INSTRUMENTATION_${moduleNameToEnvFragment(name)}_ENABLED=true`);
    }
    lines.push("");
  }

  if (disabled.length > 0) {
    lines.push("# Explicitly disabled instrumentations");
    for (const name of [...disabled].sort()) {
      lines.push(`OTEL_INSTRUMENTATION_${moduleNameToEnvFragment(name)}_ENABLED=false`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generates JVM system property output for the instrumentation settings
 * currently assembled in the configuration builder.
 *
 * Each explicitly enabled or disabled instrumentation is rendered as a
 * -Dotel.instrumentation.<name>.enabled=true/false argument. Module names
 * are preserved as-is (hyphens kept) because JVM system property names
 * follow the otel.instrumentation.<name> convention directly.
 */
export function generateSystemProperties(
  state: ConfigurationBuilderState,
  options?: OutputFormatOptions
): string {
  const date = new Date().toISOString().slice(0, 10);
  const { enabled, disabled } = readInstrumentationLists(state.values);
  const lines = buildSysPropHeader(date, options?.javaAgentVersion);
  lines.push("");

  if (enabled.length === 0 && disabled.length === 0) {
    lines.push(...NO_CUSTOMIZATIONS_LINES);
    return lines.join("\n") + "\n";
  }

  if (enabled.length > 0) {
    lines.push("# Explicitly enabled instrumentations");
    for (const name of [...enabled].sort()) {
      lines.push(`-Dotel.instrumentation.${name}.enabled=true`);
    }
    lines.push("");
  }

  if (disabled.length > 0) {
    lines.push("# Explicitly disabled instrumentations");
    for (const name of [...disabled].sort()) {
      lines.push(`-Dotel.instrumentation.${name}.enabled=false`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
