/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { describe, it, expect } from "vitest";
import type { ConfigurationBuilderState, ConfigValues } from "@/types/configuration-builder";
import { generateEnvVars, generateSystemProperties } from "./env-var-generator";

function makeState(overrides: ConfigValues = {}): ConfigurationBuilderState {
  return {
    version: "1.0.0",
    values: overrides,
    enabledSections: {},
    validationErrors: {},
    isDirty: false,
  };
}

function stateWithInstrumentations(
  enabled: string[],
  disabled: string[]
): ConfigurationBuilderState {
  if (enabled.length === 0 && disabled.length === 0) {
    return makeState();
  }
  const inst: ConfigValues = {};
  if (enabled.length > 0) inst.enabled = enabled;
  if (disabled.length > 0) inst.disabled = disabled;
  return makeState({
    distribution: {
      javaagent: {
        instrumentation: inst,
      },
    },
  });
}

// ---- generateEnvVars --------------------------------------------------------

describe("generateEnvVars", () => {
  it("includes the standard header comment", () => {
    const out = generateEnvVars(makeState());
    expect(out).toContain("# OpenTelemetry Java Agent - Instrumentation Settings");
    expect(out).toContain("# Generated by Ecosystem Explorer");
  });

  it("includes the java agent version when supplied", () => {
    const out = generateEnvVars(makeState(), { javaAgentVersion: "2.27.0" });
    expect(out).toContain("# Java agent: 2.27.0");
  });

  it("does not include java agent version when omitted", () => {
    const out = generateEnvVars(makeState());
    expect(out).not.toContain("# Java agent:");
  });

  it("shows 'no customizations' message when no instrumentations are set", () => {
    const out = generateEnvVars(makeState());
    expect(out).toContain("# No instrumentation customizations configured.");
    // Only non-comment, non-blank lines should be absent (header comments may reference the pattern)
    const settingLines = out.split("\n").filter((l) => !l.startsWith("#") && l.trim() !== "");
    expect(settingLines.length).toBe(0);
  });

  it("renders explicitly disabled instrumentations", () => {
    const out = generateEnvVars(stateWithInstrumentations([], ["jdbc"]));
    expect(out).toContain("OTEL_INSTRUMENTATION_JDBC_ENABLED=false");
    expect(out).not.toContain("OTEL_INSTRUMENTATION_JDBC_ENABLED=true");
  });

  it("renders explicitly enabled instrumentations", () => {
    const out = generateEnvVars(stateWithInstrumentations(["spring-webmvc"], []));
    expect(out).toContain("OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED=true");
  });

  it("converts hyphens to underscores and uppercases the module name", () => {
    const out = generateEnvVars(stateWithInstrumentations([], ["http-url-connection"]));
    expect(out).toContain("OTEL_INSTRUMENTATION_HTTP_URL_CONNECTION_ENABLED=false");
    expect(out).not.toContain("http-url-connection");
  });

  it("outputs both enabled and disabled sections when both are present", () => {
    const out = generateEnvVars(stateWithInstrumentations(["jdbc"], ["spring-webmvc"]));
    expect(out).toContain("OTEL_INSTRUMENTATION_JDBC_ENABLED=true");
    expect(out).toContain("OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED=false");
    expect(out).toContain("# Explicitly enabled instrumentations");
    expect(out).toContain("# Explicitly disabled instrumentations");
  });

  it("sorts module names alphabetically within each section", () => {
    const out = generateEnvVars(stateWithInstrumentations([], ["spring-webmvc", "jdbc", "apache-httpclient"]));
    // Filter to only actual setting lines (not header comment examples)
    const settingLines = out.split("\n").filter((l) => l.startsWith("OTEL_INSTRUMENTATION_"));
    expect(settingLines).toHaveLength(3);
    expect(settingLines[0]).toContain("APACHE_HTTPCLIENT");
    expect(settingLines[1]).toContain("JDBC");
    expect(settingLines[2]).toContain("SPRING_WEBMVC");
  });

  it("does not include SDK settings note to point to YAML", () => {
    const out = generateEnvVars(stateWithInstrumentations(["jdbc"], []));
    expect(out).toContain("declarative YAML");
  });

  it("returns output that ends with a newline", () => {
    const out = generateEnvVars(makeState());
    expect(out.endsWith("\n")).toBe(true);
  });
});

// ---- generateSystemProperties -----------------------------------------------

describe("generateSystemProperties", () => {
  it("includes the standard header comment", () => {
    const out = generateSystemProperties(makeState());
    expect(out).toContain("# OpenTelemetry Java Agent - JVM System Properties");
    expect(out).toContain("# Generated by Ecosystem Explorer");
  });

  it("includes the java agent version when supplied", () => {
    const out = generateSystemProperties(makeState(), { javaAgentVersion: "2.28.0" });
    expect(out).toContain("# Java agent: 2.28.0");
  });

  it("shows 'no customizations' message when no instrumentations are set", () => {
    const out = generateSystemProperties(makeState());
    expect(out).toContain("# No instrumentation customizations configured.");
    // Only non-comment, non-blank lines should be absent (header comments may reference the pattern)
    const settingLines = out.split("\n").filter((l) => !l.startsWith("#") && l.trim() !== "");
    expect(settingLines.length).toBe(0);
  });

  it("renders disabled instrumentations as -D JVM arguments", () => {
    const out = generateSystemProperties(stateWithInstrumentations([], ["jdbc"]));
    expect(out).toContain("-Dotel.instrumentation.jdbc.enabled=false");
  });

  it("renders enabled instrumentations as -D JVM arguments", () => {
    const out = generateSystemProperties(stateWithInstrumentations(["spring-webmvc"], []));
    expect(out).toContain("-Dotel.instrumentation.spring-webmvc.enabled=true");
  });

  it("preserves hyphens in module names (sys prop convention uses hyphens, not underscores)", () => {
    const out = generateSystemProperties(stateWithInstrumentations([], ["http-url-connection"]));
    expect(out).toContain("-Dotel.instrumentation.http-url-connection.enabled=false");
    expect(out).not.toContain("http_url_connection");
  });

  it("outputs both enabled and disabled when both are present", () => {
    const out = generateSystemProperties(stateWithInstrumentations(["jdbc"], ["spring-webmvc"]));
    expect(out).toContain("-Dotel.instrumentation.jdbc.enabled=true");
    expect(out).toContain("-Dotel.instrumentation.spring-webmvc.enabled=false");
  });

  it("sorts module names alphabetically within each section", () => {
    const out = generateSystemProperties(stateWithInstrumentations([], ["spring-webmvc", "jdbc", "apache-httpclient"]));
    // Filter to only actual setting lines (not header comment examples)
    const settingLines = out.split("\n").filter((l) => l.startsWith("-Dotel.instrumentation."));
    expect(settingLines).toHaveLength(3);
    expect(settingLines[0]).toContain("apache-httpclient");
    expect(settingLines[1]).toContain("jdbc");
    expect(settingLines[2]).toContain("spring-webmvc");
  });

  it("includes a hint to look at the JVM launch command example", () => {
    const out = generateSystemProperties(makeState());
    expect(out).toContain("java -Dotel.instrumentation.jdbc.enabled=false -jar app.jar");
  });

  it("returns output that ends with a newline", () => {
    const out = generateSystemProperties(makeState());
    expect(out.endsWith("\n")).toBe(true);
  });
});
